return {
    ["workshop-1571581787"]={
      configuration_options={
        ANIMALSTACK=true,
        EGGSTACK=true,
        MAXSTACKSIZE=99,
        TOOLSTACK=false,
        TRAPSTACK=true 
      },
      enabled=true 
    },
    ["workshop-1813311384"]={
      configuration_options={ DAY_RAIN=true, DELAY_RAIN=5, HEALTH_RAIN=1, WET_RAIN=false },
      enabled=true 
    },
    ["workshop-2414471353"]={ configuration_options={ gamemode="YES", wuqimode="NO" }, enabled=true },
    ["workshop-2519917081"]={
      configuration_options={
        [""]=0,
        ["Auto Respawn"]=0,
        ["Basic Stats"]=0,
        ["Language/言語"]=0,
        Others=0,
        ["Watame Katana"]=0,
        ["Watame Shogun Helm"]=0,
        enable_watame_auto_respawn=true,
        enable_watame_katana_crit_shogun_set=true,
        watame_auto_respawn_delay=8,
        watame_auto_respawn_frequency=2,
        watame_clothes=false,
        watame_dmg=0.8,
        watame_health=125,
        watame_hunger=200,
        watame_hunger_rate=1,
        watame_katana_atk_damage=34,
        watame_katana_crit_chance1=20,
        watame_katana_crit_multi1=2.5,
        watame_katana_usage=150,
        watame_language="AUTO",
        watame_sanity=150,
        watame_shogun_absoption=0.6,
        watame_shogun_atk_buff=1.15,
        watame_shogun_cold_insulation=60,
        watame_shogun_durability=840,
        watame_speed=1,
        watame_starting=2,
        watame_voice="willow" 
      },
      enabled=true 
    },
    ["workshop-2533421726"]={ configuration_options={ saber_cn=true, saber_weapon=999999 }, enabled=true },
    ["workshop-2536607878"]={
      configuration_options={
        divider=5,
        random_health_value=0,
        random_range=0,
        send_unknwon_prefabs=false,
        show_type=0,
        unknwon_prefabs=1,
        use_blacklist=true 
      },
      enabled=true 
    },
    ["workshop-2584216489"]={ configuration_options={  }, enabled=true },
    ["workshop-2589174774"]={ configuration_options={  }, enabled=true },
    ["workshop-2589712698"]={
      configuration_options={
        amulet_slot=true,
        backpack_slot=true,
        chesspiece_fix=true,
        compass_slot=true,
        drop_hand_item_when_heavy=true,
        enable_ui=0,
        render_strategy="neck",
        show_compass=false,
        slots_num=0,
        snurtle_remove_armor=true 
      },
      enabled=true 
    },
    ["workshop-363112314"]={ configuration_options={  }, enabled=true },
    ["workshop-378160973"]={
      configuration_options={
        ENABLEPINGS=true,
        FIREOPTIONS=2,
        OVERRIDEMODE=false,
        SHAREMINIMAPPROGRESS=true,
        SHOWFIREICONS=true,
        SHOWPLAYERICONS=true,
        SHOWPLAYERSOPTIONS=2 
      },
      enabled=true 
    },
    ["workshop-462434129"]={
      configuration_options={
        MOD_RESTART_ALLOW_KILL=true,
        MOD_RESTART_ALLOW_RESTART=true,
        MOD_RESTART_ALLOW_RESURRECT=true,
        MOD_RESTART_CD_BONUS=0,
        MOD_RESTART_CD_KILL=3,
        MOD_RESTART_CD_MAX=0,
        MOD_RESTART_CD_RESTART=5,
        MOD_RESTART_CD_RESURRECT=7,
        MOD_RESTART_FORCE_DROP_MODE=0,
        MOD_RESTART_IGNORING_ADMIN=true,
        MOD_RESTART_MAP_SAVE=2,
        MOD_RESTART_RESURRECT_HEALTH=0,
        MOD_RESTART_TRIGGER_MODE=1,
        MOD_RESTART_WELCOME_TIPS=true,
        MOD_RESTART_WELCOME_TIPS_TIME=6 
      },
      enabled=true 
    },
    ["workshop-501385076"]={
      configuration_options={
        quick_cook_on_fire=true,
        quick_harvest=true,
        quick_pick_cactus=true,
        quick_pick_plant_normal_ground=true 
      },
      enabled=true 
    }
  }
